name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Package
        run: mvn -B package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: realms-sync
          path: '**/target/*.jar'
